### ISSUE TITLE
Error when testing or deploying a contract containing a library function call.

### ISSUE THREAD

**Issue by kalloc** [0xPhaze/upgrade-scripts#6] opened 2023-03-15 13:24 UTC
Hi.

Thank you very much for your work. 
But, I found a mistake while using it.
If the contract under test contains a library function call, the testing fails.
I made a repo with an error https://github.com/8gen/0xPhaze-upgrade-script-bug, so you may repeat.

How I call function:
```solidity
..
import {Lib} from "./library/Lib.sol";
..
number = newNumber + Lib.x();
..
```

```bash
$ forge test

[⠆] Compiling...
No files changed, compilation skipped
2023-03-15T12:59:19.471056Z ERROR forge::runner: setUp failed reason="failed to read from \"../out/Counter/Counter.json\": No such file or directory (os error 2)" contract=0x7fa9385be102ac3eac297483dd6233d62b3e1496

Running 1 test for test/Counter.t.sol:CounterTest
[FAIL. Reason: Setup failed: failed to read from "../out/Counter/Counter.json": No such file or directory (os error 2)] setUp() (gas: 0)
Test result: FAILED. 0 passed; 1 failed; finished in 965.23µs

Failing tests:
Encountered 1 failing test in test/Counter.t.sol:CounterTest
[FAIL. Reason: Setup failed: failed to read from "../out/Counter/Counter.json": No such file or directory (os error 2)] setUp() (gas: 0)

Encountered a total of 1 failing tests, 0 tests succeeded
```

**Comment by kalloc** [comment] 2023-03-15 13:35
Maybe the problem in foundry (https://github.com/foundry-rs/book/issues/1361)

**Comment by 0xPhaze** [comment] 2023-03-15 16:21
The issue is that the artifact folder now has multiple files with the included lib and you should specify the contract location via "Counter.sol:Counter". 

However, I added an extra search for "{Contract}.sol:{Contract}" and 9112da4 should fix this. Also should have better error logging now. Let me know if it works.

**Comment by 0xPhaze** [comment] 2023-03-15 16:32
@kalloc actually there seems to be another issue related to this. I think foundry doesn't handle public library linking well. You might want to change
```solidity
function x() public pure returns (uint256) {
    return X;
}
```
to
```solidity
function x() internal pure returns (uint256) {
    return X;
}
```

**Comment by kalloc** [comment] 2023-03-15 16:33
Yes, I did it. And I learned that it is foundry issue. https://github.com/8gen/foundry-library-linking-bug <https://github.com/8gen/foundry-library-linking-bug> I did simplified example

**Comment by 0xPhaze** [comment] 2023-03-20 17:41
Closing this here then for now

**Closed as completed by 0xPhaze** 2023-03-20 17:41 UTC
